name: Test

on:
    pull_request:
        branches: [main, devel]

permissions:
    contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  scope: '@daniele-tentoni'
                  registry-url: 'https://npm.pkg.github.com'
            - run: |
                  npm ci
                  npm run format:check
                  npm run test:unit
